# Generated by Django 4.1.7 on 2023-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('director', 'Director'), ('secretary', 'Secretary'), ('associate director', 'Associate Director')], default='secretary', max_length=50),
        ),
    ]
