# Generated by Django 4.1.7 on 2023-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('secretary', 'Secretary'), ('director', 'Director'), ('associate director', 'Associate Director')], default='secretary', max_length=150),
        ),
    ]
